### ISSUE TITLE
Chapter 5 needs to be finished

### ISSUE THREAD

**Issue by aloctavodia** [aloctavodia/Statistical-Rethinking-with-Python-and-PyMC3#11]

**Comment by gladomat** [comment]
I would like to get involved, however, I haven't read or worked through the book (although it's on my desk right now). How hard would it be to work through R-code and port it to python? My python skills aren't outstanding but I can manage.

**Comment by aloctavodia** [comment]
Thanks! It will be really helpful if you can contribute.

To evaluate how easy/hard is for you to port the code you should probably
check some of the already ported code and compare that with the code in the
book. Don't hesitate to ask questions if you have them.

El ene 9, 2017 8:20 AM, "gladomat" <notifications@github.com> escribió:

I would like to get involved, however, I haven't read or worked through the
book (although it's on my desk right now). How hard would it be to work
through R-code and port it to python? My python skills aren't outstanding
but I can manage.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/aloctavodia/Statistical-Rethinking-with-Python-and-PyMC3/issues/11#issuecomment-271261294>,
or mute the thread

**Comment by agustinaarroyuelo** [comment]
Chapter five is finished.
