### ISSUE TITLE
Chapter 6 needs to be finished

### ISSUE THREAD

**Issue by aloctavodia** [aloctavodia/Statistical-Rethinking-with-Python-and-PyMC3#12]

**Comment by gladomat** [comment]
I'll tackle the rest of this chapter, if you don't mind.

**Comment by aloctavodia** [comment]
Is OK with me, but we should coordinate with @agustinaarroyuelo. I think she was about to work on this chapter.

**Comment by gladomat** [comment]
Ok, well I added stuff up to 6.8. If @agustinaarroyuelo wants to keep working on it, that's fine. I'll get to work on Chapter 8 then.

**Comment by aloctavodia** [comment]
OK, Chapter 8 has been assigned to @AustinRochford. What about working on chapter 9?

**Comment by AustinRochford** [comment]
Hi yes, I will be getting back to Chapter 8 shortly (hopefully next week)

**Comment by aloctavodia** [comment]
Great @AustinRochford, so @gladomat please check the issues list and choose one chapter you like with the label "help wanted".
