### ISSUE TITLE
Work-in-progress tracking

### ISSUE THREAD

**Issue by AustinRochford** [aloctavodia/Statistical-Rethinking-with-Python-and-PyMC3#2]
Is there a way you'd like to track progress on this?  I'd love to contribute, but don't want to duplicate a chapter someone is already working on.

**Comment by aloctavodia** [comment]
That would be great!

We can open one issue per unfinished chapter and assign a person per
chapter. What do you think?

 @agustinaarroyuelo is working on chapter 5 and I am working on chapter 6.
You can take any chapter from 7 to 14.

**Comment by AustinRochford** [comment]
Sounds great.
