### ISSUE TITLE
5.33 sum of posteriors

### ISSUE THREAD

**Issue by santiago1234** [aloctavodia/Statistical-Rethinking-with-Python-and-PyMC3#30]
Why the posterior distribution of the sum of *bl* and *br* is not in the same scale (centered at 2.05) as shown in the book (top page 144)?
thanks,

**Comment by aloctavodia** [comment]
Not sure why the values are not the same to those in the book (I will keep looking), but notice that the results of model 5.8 and model 5.9 are consistent

**Comment by santiago1234** [comment]
I see, thanks anyway (I will try to check too). I appreciate the effort you have put in making this repo, it has been a very helpful resource to learn together with the book 😊


________________________________
De: Osvaldo Martin <notifications@github.com>
Enviado: lunes, 16 de octubre de 2017 12:18 p. m.
Para: aloctavodia/Statistical-Rethinking-with-Python-and-PyMC3
CC: Santiago Medina; Author
Asunto: Re: [aloctavodia/Statistical-Rethinking-with-Python-and-PyMC3] 5.33 sum of posteriors (#30)


Not sure why the values are not the same to those in the book (I will keep looking), but notice that the results of model 5.8 and model 5.9 are consistent

**Comment by GWeindel** [comment]
Wrong scale argument in the uniform leg proportion, should be 0.1 (uniform.rvs takes sample from loc to loc+scale). I would fix it but I do not know how as I am new to GitHub.
Thanks for this resource by the way !

**Comment by aloctavodia** [comment]
Good catch @GWeindel, thanks!
