### ISSUE TITLE
Chapter 4 code 4.38 and 4.39 missing a comma.

### ISSUE THREAD

**Issue by hvillamil3** [aloctavodia/Statistical-Rethinking-with-Python-and-PyMC3#34]
The commented line for model m4_3 is missing a comma between 'mu' and alpha.
`#mu = pm.Deterministic('mu' alpha + beta * d2.weight) # try uncomenting this line and comenting the above line `

**Comment by aloctavodia** [comment]
good catch! Thank you @hvillamil3
