### ISSUE TITLE
Smaller WAIC in PyMC3

### ISSUE THREAD

**Issue by junpenglao** [aloctavodia/Statistical-Rethinking-with-Python-and-PyMC3#47]
Just wondering if anybody dig into the code to see why WAIC return from the book and rethinking is sometimes larger than we computed using `pm.compare`. It appears in some models but not the others. I dont think it is too much of a problem, as the orders return from both is the same.

**Comment by aloctavodia** [comment]
I guess in some cases is related to the way most models are fitted in the book (Laplace approximation). But in chapter 10 there is at least one example where the difference is really large. This is definitely something I want to understand.
