### ISSUE TITLE
New home for this repo

### ISSUE THREAD

**Issue by aloctavodia** [aloctavodia/Statistical-Rethinking-with-Python-and-PyMC3#49]
What about transferring this repository into an organization. Maybe inside pymc-devs? Together with other books/docs?  Thoughts @junpenglao, @AustinRochford @twiecki

**Comment by junpenglao** [comment]
I think that is a good idea.
For example, Stan has an example repo: https://github.com/stan-dev/example-models

**Comment by AustinRochford** [comment]
I also think it's a good idea.

**Comment by twiecki** [comment]
👍 @aloctavodia what do you want to name the repo?

**Comment by aloctavodia** [comment]
Not sure, but assuming that eventually we are going to put there more than one repo (and not only Statistical Rethinking), we could call it `literature`, I like how it sound and is broad enough to include things other than books (but larger than isolated examples)

**Comment by aloctavodia** [comment]
any update on this? :-)

**Comment by twiecki** [comment]
@aloctavodia What else would be put in that `literature` repo?

**Comment by junpenglao** [comment]
I can transfer mine: https://github.com/junpenglao/Bayesian-Cognitive-Modeling-in-Pymc3

The problem would be maintenance. A similar idea is a model zoo repository filled with case studies (including moving some the docs into there), which we were discussing at some point.

**Comment by aloctavodia** [comment]
Everything inside `literature` should be re-runned before every new release to guarantee nothing stop working. That not sound like a lot of maintenance work...

**Comment by twiecki** [comment]
I think I'd like this idea more (instead of separate repos) if we came up with a better name. `resources`, `training_materials`?
The benefit of separate repos is that they all have their own URL with a direct readme.

**Comment by junpenglao** [comment]
If you put a readme in the subfolder it will show up as well.

**Comment by twiecki** [comment]
That's true.

**Comment by junpenglao** [comment]
FYI, some point of references:
https://github.com/stan-dev/example-models
https://github.com/edwardlib/papers
https://github.com/tensorflow/workshops
https://github.com/pytorch/examples

**Comment by twiecki** [comment]
https://github.com/pymc-devs/resources

**Comment by aloctavodia** [comment]
I know how to transfer the repository to https://github.com/pymc-devs, but I don't know how to transfer and put it inside https://github.com/pymc-devs/resources in a single step...

**Comment by twiecki** [comment]
@aloctavodia I think you can only copy the files and start the repo fresh (maybe keep this one around?).

**Comment by aloctavodia** [comment]
The benefit of transferring ownership is that preserves history, commits, automatic redirection, etc...

**Comment by junpenglao** [comment]
I never try but it could be done: https://gist.github.com/msrose/2feacb303035d11d2d05

**Comment by junpenglao** [comment]
also https://stackoverflow.com/questions/26502970/merge-multiple-git-repositories-into-one-keeping-branches-history

**Comment by junpenglao** [comment]
OK guys I just imported the two project - go check them out ;-)

**Comment by aloctavodia** [comment]
Great, we not get automatic redirection with this solution but nevertheless is good enough for me.
