### ISSUE TITLE
Enhancement of the notebooks

### ISSUE THREAD

**Issue by junpenglao** [aloctavodia/Statistical-Rethinking-with-Python-and-PyMC3#51]
Since almost all the chapter is ported (I will also work on Chapter 14), maybe it is good to 

- [ ] add legends to the figures in the early chapter. 
- [ ] reproduce the rest of the figures shown in the book. Some of the figures are related to the analysis without code presented.

**Comment by aloctavodia** [comment]
I agree, in general. Although, I will be very careful about the _missing code_. I guess the code is not presented on purpose, maybe those figures were left as exercises for the students and hence we should not add them to the repository. One option is to ask Richard McElreath for guidance.

**Comment by junpenglao** [comment]
I see. I agree with you.

**Comment by aloctavodia** [comment]
I am working on legends and also other minor changes, like a consistent color palette.
