### ISSUE TITLE
postcheck not implemented

### ISSUE THREAD

**Issue by gladomat** [aloctavodia/Statistical-Rethinking-with-Python-and-PyMC3#62]
I know there are some functions from the rethinking package that we need to do without. I was wondering, however, if there is an implementation of `postcheck` which plots posterior predictions that can be validated against actual data. This is very helpful when reviewing models to see if they fit the data well or not.

You can find the function on [Richard's github page](https://github.com/rmcelreath/rethinking/blob/master/R/postcheck.r). It's used, for example, on page 306 of the book, code 10.27.

**Comment by aloctavodia** [comment]
Closing as this has been implemented in ArviZ
