### ISSUE TITLE
Proposal for code 6.24

### ISSUE THREAD

**Issue by larry-lu** [aloctavodia/Statistical-Rethinking-with-Python-and-PyMC3#73]
The `pm.compare` function is using a different syntax (I am using version 3.5). Instead of the old syntax which takes two lists for traces and models respectively, the new syntax takes a dictionary with model:trace as key-value pairs.

The old code in 6.24:

```python
compare_df = pm.compare([trace_m6_11, trace_m6_12, trace_m6_13, trace_m6_14], 
                        [m6_11, m6_12, m6_13, m6_14], 
                        method='pseudo-BMA')
```
should be revised to 

```python
compare_df = pm.compare({m6_11: trace_m6_11, 
                         m6_12: trace_m6_12, 
                         m6_13: trace_m6_13, 
                         m6_14: trace_m6_14}, 
                         method='pseudo-BMA')
```

**Comment by junpenglao** [comment]
Please find the up to date repo: https://github.com/pymc-devs/resources/blob/master/Rethinking/Chp_06.ipynb.
