### ISSUE TITLE
How to fix error?

### ISSUE THREAD

**Issue by nguyenhoaiThanhbk2811** [aloctavodia/Statistical-Rethinking-with-Python-and-PyMC3#74]

**Comment by nguyenhoaiThanhbk2811** [comment]
import pymc3 as pm

basic_model = pm.Model()

with basic_model:

    # Priors for unknown model parameters
    alpha = pm.Normal('alpha', mu=0, sigma=10)
    beta = pm.Normal('beta', mu=0, sigma=10, shape=2)
    sigma = pm.HalfNormal('sigma', sigma=1)

    # Expected value of outcome
    mu = alpha + beta[0]*X1 + beta[1]*X2

    # Likelihood (sampling distribution) of observations
    Y_obs = pm.Normal('Y_obs', mu=mu, sigma=sigma, observed=Y)

map_estimate = pm.find_MAP(model=basic_model)
map-estimate

when I run the code it has as error 
C:\Users\hoaithanh\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "C:/Users/hoaithanh/Desktop/hocpython/chapter2.py", line 8, in <module>
    alpha = pm.Normal('alpha', mu=0, sigma=10)
  File "C:\Users\hoaithanh\Anaconda3\lib\site-packages\pymc3\distributions\distribution.py", line 41, in __new__
    dist = cls.dist(*args, **kwargs)
  File "C:\Users\hoaithanh\Anaconda3\lib\site-packages\pymc3\distributions\distribution.py", line 52, in dist
    dist.__init__(*args, **kwargs)
  File "C:\Users\hoaithanh\Anaconda3\lib\site-packages\pymc3\distributions\continuous.py", line 404, in __init__
    super(Normal, self).__init__(**kwargs)
  File "C:\Users\hoaithanh\Anaconda3\lib\site-packages\pymc3\distributions\distribution.py", line 180, in __init__
    shape, dtype, defaults=defaults, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'sigma'

> 
Thanks you

**Comment by aloctavodia** [comment]
You have to use `sd` instead of `sigma`. The next version of PyMC3 (3.7) will allow to use `sigma` or `sd`, or you can install PyMC3 from master (not recommended).


Thus your model should be 
```python
with pm.Model() as basic_model:
    alpha = pm.Normal('alpha', mu=0, sd=10)
    beta = pm.Normal('beta', mu=0, sd=10, shape=2)
    sigma = pm.HalfNormal('sigma', sd=1)

    # Expected value of outcome
    mu = alpha + beta[0]*X1 + beta[1]*X2

    # Likelihood (sampling distribution) of observations
    Y_obs = pm.Normal('Y_obs', mu=mu, sd=sigma, observed=Y)
    trace = pm.sample()
```
