### ISSUE TITLE
New code for Statistcal Rethinking 2nd edition

### ISSUE THREAD

**Issue by Mind-The-Data** [aloctavodia/Statistical-Rethinking-with-Python-and-PyMC3#75]
I've been working through the not yet released 2nd version of McElreath's book and have been using this repository to help guide me along the way. Its been extremely helpful, thanks! As of about ch.6 there is enough difference between the versions that it has become quite difficult to use. Any interest in getting a head start on the 2nd edition code translations so when he releases it, the code with be available in python as well?  The 2nd edition can be found on his website w/ a password on one of the first 2019 youtube videos.

**Comment by gladomat** [comment]
I second this. However, we should be working on the pymc3 repository instead. That's the official repo right now: https://github.com/pymc-devs/resources/tree/master/Rethinking

**Comment by aloctavodia** [comment]
Hi guys, 

This is definitively something I will like to do, so I am really glad to hear you are offering help. 
We (pymc-devs) have been talking to Richard McElreath, and he is also on board. Nevertheless, he think we should port the code once he has a more advanced version of the book, as he is planning to make too many changes to the available drafr. He will have a more advanced draft version in about 6 months.

**Comment by aloctavodia** [comment]
Closing as the code for Statistical Rethinking is being ported https://github.com/pymc-devs/resources/tree/master/Rethinking_2
