### ISSUE TITLE
Chp_04 doesnt load

### ISSUE THREAD

**Issue by willgp94** [aloctavodia/Statistical-Rethinking-with-Python-and-PyMC3#76]
I get the message saying 

> Sorry, something went wrong. Reload?

. I believe this happens for other Chapters as well.

**Comment by aloctavodia** [comment]
Hi @willgp94 that's a message from GitHub, we do not have control over this. Sometimes you just need to refresh the page a couple of times to make it work. Also notice that this repository has been deprecated in favor of this [one](https://github.com/pymc-devs/resources/tree/master/Rethinking), please check that repository for updates.
