### ISSUE TITLE
Homework solutions?

### ISSUE THREAD

**Issue by bluesky314** [aloctavodia/Statistical-Rethinking-with-Python-and-PyMC3#77]
What about the homework solutions? Where are they?

**Comment by aloctavodia** [comment]
By request of the author the homework solutions are not public. Also notice that this repository is deprecated in favor of this one https://github.com/pymc-devs/resources/tree/master/Rethinking

**Comment by aloctavodia** [comment]
We agreed to add this to https://github.com/pymc-devs/resources/tree/master/Rethinking
