### ISSUE TITLE
Code in 4.54,4.58

### ISSUE THREAD

**Issue by bluesky314** [aloctavodia/Statistical-Rethinking-with-Python-and-PyMC3#78]
Cant understand this piece of code in 4.54 and 4.58:
```
weigth_seq = np.arange(25, 71)
# Given that we have a lot of samples we can use less of them for plotting (or we can use all!)
chain_N_thinned = chain_N[::10]
mu_pred = np.zeros((len(weigth_seq), len(chain_N_thinned)*chain_N.nchains))
for i, w in enumerate(weigth_seq):
    mu_pred[i] = chain_N_thinned['alpha'] + chain_N_thinned['beta'] * w

```
What is chain_N[::10]? and chain_N.nchains doing? What is mu_pred supposed to be?

**Comment by aloctavodia** [comment]
`chain_N[::10]` is taking every-other 10th sample from chain_N. This is known as "slicing" in python with the syntax `a[start:stop:step]`. Where `a` is an object like a list a numpy array or a PyMC3 trace. Here we are omitting start and stop and thus we are slicing the entire trace.

`chain_N.nchains` returns the number of chains stored in the trace objects (the number of chains sampled by PyMC3)

mu_pred corresponds to the predicted values for each "x" value in the range 25 to 71 (weigth_seq). If you "connect the dots" you can think of these values as plausible lines according to  the model and data.

**Comment by bluesky314** [comment]
Thanks alot. I had abit of confusion about chain_N.nchains, what does 'number of chains mean' in 
<MultiTrace: 2 chains, 1000 iterations, 5 variables> ? I understand the rest.

**Comment by aloctavodia** [comment]
By default PyMC3 tries to run more than one chain as this allow some tests to be performed and if you have a multicore processor then its take basically the same time (but you get more samples!). A chain is a MCMC sample from the posterior. Each chain is independent from the rest.
