### ISSUE TITLE
Why should both betas have same distribution in quadratic regression?

### ISSUE THREAD

**Issue by bluesky314** [aloctavodia/Statistical-Rethinking-with-Python-and-PyMC3#79]
In 4.66, we set beta to generate two numbers for our quadratic model so both are generated from the same distribution. But the book generates it from two different distributions. Why would we do this? Doesn't this decrease the flexibility of the model?

```
with pm.Model() as m_4_5:
    alpha = pm.Normal('alpha', mu=178, sd=100)
    
    beta = pm.Normal('beta', mu=0, sd=10, shape=2) # shape of 2 generates two betas
    sigma = pm.Uniform('sigma', lower=0, upper=50)
    mu = pm.Deterministic('mu', alpha + beta[0] * d.weight_std + beta[1] * d.weight_std2)
    height = pm.Normal('height', mu=mu, sd=sigma, observed=d.height)
    trace_4_5 = pm.sample(1000, tune=1000)
```

**Comment by aloctavodia** [comment]
By doing `beta = pm.Normal('beta', mu=0, sd=10, shape=2)` you are sampling from two **independent** normal distributions each one with mean 0 and standard deviation 10.  Thus using  `shape=2 ` is a more convenient way of writing

```python
beta1 = pm.Normal('beta1', mu=0, sd=10)
beta2 = pm.Normal('beta2', mu=0, sd=10)
```

**Comment by aloctavodia** [comment]
BTW this repository has been deprecated in favor of this [one](https://github.com/pymc-devs/resources/tree/master/Rethinking)
